Pp delete comment
nss-day-cohort-46/rare-rest-rare-api-cool-cake pull request #54
Opened 2021-05-17 20:20 UTC by phillipphan

Description:
Backend code for creating comments is complete.

Testing Instructions:

Postman URL:
```
http://localhost:8000/comments/1
```

Make a DELETE request in Postman and check the database to see if the comment with id = 1 is deleted.

2021-05-18 14:12 UTC, daprieu approved these changes

2021-05-18 15:34 UTC, Daniel-L-Ross requested changes
As user 3, I was able to delete a comment that user 1 made.

2021-05-18 19:05 UTC, daprieu approved these changes

2021-05-19 16:34 UTC, Daniel-L-Ross approved these changes
Good fix!

2021-05-19 16:51 UTC, merged