Pp edit comment
nss-day-cohort-46/rare-rest-rare-api-cool-cake pull request #55
Opened 2021-05-17 20:28 UTC by phillipphan

Description:

Backend for editing a comment is finished

Testing Instructions:

Postman URL:
Change the id of the URL to a comment that you have in the database, if you don't have id = 2.
```
http://localhost:8000/comments/2
```

Postman Object:
{
    "postId": 1,
    "content": "edited new comment",
    "createdOn": "2016-05-18T15:37:36.993048Z"
}

Make a PUT request and check the database to see if the post was changed.

2021-05-18 14:14 UTC, daprieu approved these changes

2021-05-18 15:38 UTC, Daniel-L-Ross requested changes
User number 2 was able to edit user number 1's comment, database updated it and showed that the comment is attributed to user 2.

2021-05-18 19:12 UTC, daprieu approved these changes

2021-05-19 16:35 UTC, Daniel-L-Ross approved these changes

2021-05-19 16:51 UTC, merged